version: 2

sources:
  - name: dv_pizza_parlor
    description: "A dbt model for Pizza Parlor"
    database: "{{ env_var('DBT_DATABASE','PIZZA_PARLOR_DB') }}"
    schema: STAGE_SCHEMA
    tables:
      - name: STG_CUSTOMERS
      - name: STG_ORDERS
      - name: STG_ORDER_ITEMS
      - name: STG_PIZZAS
      - name: STG_INGREDIENTS
      - name: STG_PIZZA_INGREDIENTS

      